### ISSUE TITLE
Error while using dl_docs with a high enough --last_days parameter (or none)

### ISSUE THREAD

**Issue by evo-de** [pytr-org/pytr#136]
**Description of the bug**
The command `pytr dl_docs --debug --last_days xxx .` (and `pytr dl_docs --debug .` is terminating with an error message.

**To Reproduce**

1. Go to 'folder I've always been using'
2. Ran the command `pytr dl_docs --debug .`
3. See error

**Expected behavior**
All documents etc. being successfully downloaded.

**Error log**

```
2024-11-01 09:20:57+0100 timeline  INFO     494/494: xxx -- Fertig - 2024-10-01T07:53:44
2024-11-01 09:20:57+0100 dl        DEBUG    File Transaktionsbestätigung\ Transaktionsbestätigung - xxx.pdf already in queue. Append document id 0f49107a-79df-4c79-8a78-51357cdecbba...
2024-11-01 09:20:57+0100 dl        DEBUG    file Transaktionsbestätigung\ Transaktionsbestätigung - xxx (0f49107a-79df-4c79-8a78-51357cdecbba).pdf already exists. Skipping...
2024-11-01 09:20:57+0100 timeline  INFO     Received all details
2024-11-01 09:20:57+0100 transactions INFO     Write deposit entries
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Scripts\pytr.exe\__main__.py", line 7, in <module>
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytr\main.py", line 219, in main
    asyncio.get_event_loop().run_until_complete(dl.dl_loop())
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytr\dl.py", line 81, in dl_loop
    await self.tl.process_timelineDetail(response, self)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytr\timeline.py", line 175, in process_timelineDetail
    export_transactions(dl.output_path / 'all_events.json', dl.output_path / 'account_transactions.csv', sort = dl.sort_export)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytr\transactions.py", line 51, in export_transactions
    lines = formatter.format_header() + "".join(lines)
                                        ^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytr\transactions.py", line 47, in <lambda>
    events = map(lambda x: Event.from_dict(x), timeline)
                           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytr\event.py", line 109, in from_dict
    fees, isin, note, shares, taxes = cls._parse_type_dependent_params(
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytr\event.py", line 148, in _parse_type_dependent_params
    shares, fees = cls._parse_shares_and_fees(event_dict)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytr\event.py", line 213, in _parse_shares_and_fees
    return return_vals["shares"], return_vals.get("fees", None)
           ~~~~~~~~~~~^^^^^^^^^^
KeyError: 'shares'
```

**Environment**

- OS: Win10
- pytr version: 0.3.0

**Additional context**
I've noticed, that using e.g. `--last_days 320` works fine, but at roughly 340 days the error is thrown. There are 228 results at 320 days (which still works), and the error is thrown at 340 days with 238 results.

**Comment by pinzutu** [comment]
You probably have a currently ill supported event type in your timeline. Could you close in on the problematic event by varying the date and share its (redacted) json entry?

**Comment by harakaio** [comment]
Hi there,
having the same issue here. 
Usually I'm downloading with the following command `pytr dl_docs --last_days 0 --workers 16 C:\tmp\TR`

I've tracked it down with varying the --last_days parameter:
- working: 300-304 days
- not working: 305-365 days

This date is from today calculated the 02.01.2024. Maybe there is an issue with the change of the year?

**Comment by evo-de** [comment]
So the problem starts 333d ago from today (03.11.2024) on 06.12.2023. According to the TR log nothing happend on that day, but on 07.12 I bought a bond (which does not seem to be traded on TR anymore).

from `events_with_documents.json`:
```
{
    "action": {
        "payload": "xxx",
        "type": "timelineDetail"
    },
    "amount": {
        "currency": "EUR",
        "fractionDigits": 2,
        "value": -xxx.xx
    },
    "badge": null,
    "details": {
        "id": "xxx",
        "sections": [
            {
                "action": {
                    "payload": "XS2326497802",
                    "type": "instrumentDetail"
                },
                "data": {
                    "icon": "logos/bondissuer-529900381YTPHVY9AI06/v2",
                    "status": "executed",
                    "subtitleText": null,
                    "timestamp": "2023-12-07T06:59:36.156+0000"
                },
                "title": "Du hast xxx,xx €  investiert",
                "type": "header"
            },
            {
                "action": null,
                "data": [
                    {
                        "detail": {
                            "functionalStyle": "EXECUTED",
                            "text": "Ausgeführt",
                            "type": "status"
                        },
                        "style": "plain",
                        "title": "Status"
                    },
                    {
                        "detail": {
                            "action": null,
                            "text": "Kauf",
                            "trend": null,
                            "type": "text"
                        },
                        "style": "plain",
                        "title": "Orderart"
                    },
                    {
                        "detail": {
                            "action": null,
                            "text": "Anleihe Apr. 2026",
                            "trend": null,
                            "type": "text"
                        },
                        "style": "plain",
                        "title": "Asset"
                    }
                ],
                "title": "Übersicht",
                "type": "table"
            },
            {
                "action": {
                    "payload": {
                        "sections": [
                            {
                                "action": null,
                                "title": "Transaktion",
                                "type": "title"
                            },
                            {
                                "action": null,
                                "data": [
                                    {
                                        "detail": {
                                            "action": null,
                                            "text": "xxx,xx €",
                                            "trend": null,
                                            "type": "text"
                                        },
                                        "style": "plain",
                                        "title": "Nominale"
                                    },
                                    {
                                        "detail": {
                                            "action": null,
                                            "text": "xx,xx %",
                                            "trend": null,
                                            "type": "text"
                                        },
                                        "style": "plain",
                                        "title": "Kurs"
                                    },
                                    {
                                        "detail": {
                                            "action": null,
                                            "text": "xxx,xx €",
                                            "trend": null,
                                            "type": "text"
                                        },
                                        "style": "highlighted",
                                        "title": "Order"
                                    }
                                ],
                                "title": null,
                                "type": "table"
                            },
                            {
                                "action": null,
                                "data": [
                                    {
                                        "detail": {
                                            "action": null,
                                            "text": "xxx,xx €",
                                            "trend": null,
                                            "type": "text"
                                        },
                                        "style": "plain",
                                        "title": "Order"
                                    },
                                    {
                                        "detail": {
                                            "action": null,
                                            "text": "x,xx €",
                                            "trend": null,
                                            "type": "text"
                                        },
                                        "style": "plain",
                                        "title": "Stückzinsen"
                                    },
                                    {
                                        "detail": {
                                            "action": null,
                                            "text": "x,xx €",
                                            "trend": null,
                                            "type": "text"
                                        },
                                        "style": "plain",
                                        "title": "Gebühr"
                                    },
                                    {
                                        "detail": {
                                            "action": null,
                                            "text": "xxx,xx €",
                                            "trend": null,
                                            "type": "text"
                                        },
                                        "style": "highlighted",
                                        "title": "Gesamt"
                                    }
                                ],
                                "title": null,
                                "type": "table"
                            }
                        ]
                    },
                    "type": "infoPage"
                },
                "data": [
                    {
                        "detail": {
                            "action": null,
                            "text": "x,xx €",
                            "trend": null,
                            "type": "text"
                        },
                        "style": "plain",
                        "title": "Gebühr"
                    },
                    {
                        "detail": {
                            "action": null,
                            "text": "xxx,xx €",
                            "trend": null,
                            "type": "text"
                        },
                        "style": "highlighted",
                        "title": "Gesamt"
                    }
                ],
                "title": "Transaktion",
                "type": "table"
            },
            {
                "action": null,
                "data": [
                    {
                        "action": {
                            "payload": "https://traderepublic-data-production.s3.eu-central-1.amazonaws.com/timeline/xxx",
                            "type": "browserModal"
                        },
                        "detail": "07.12.2023",
                        "id": "xxx",
                        "local_filepath": "Abrechnung\\2023-12-07 Abrechnung - Anleihe Apr. 2026.pdf",
                        "postboxType": "SECURITIES_SETTLEMENT",
                        "title": "Abrechnung"
                    },
                    {
                        "action": {
                            "payload": "https://traderepublic-data-production.s3.eu-central-1.amazonaws.com/timeline/xxx",
                            "type": "browserModal"
                        },
                        "detail": "07.12.2023",
                        "id": "xxx",
                        "local_filepath": "Kosteninformation\\2023-12-07 Kosteninformation - Anleihe Apr. 2026.pdf",
                        "postboxType": "COSTS_INFO_BUY_V2",
                        "title": "Kosteninformation"
                    }
                ],
                "title": "Dokumente",
                "type": "documents"
            },
            {
                "action": null,
                "data": [
                    {
                        "detail": {
                            "action": {
                                "payload": {
                                    "contextCategory": "NHC",
                                    "contextParams": {
                                        "chat_flow_key": "NHC_0029_wealth_bonds_past_trade_execution",
                                        "groupId": "xxx",
                                        "timelineEventId": "xxx"
                                    }
                                },
                                "type": "customerSupportChat"
                            },
                            "icon": "logos/timeline_communication/v2",
                            "style": "highlighted",
                            "type": "listItemAvatarDefault"
                        },
                        "style": "plain",
                        "title": "Report a issue"
                    }
                ],
                "title": "Hilfe",
                "type": "table"
            }
        ]
    },
    "eventType": "ORDER_EXECUTED",
    "has_docs": true,
    "icon": "logos/bondissuer-529900381YTPHVY9AI06/v2",
    "id": "xxx",
    "source": "timelineTransaction",
    "status": "EXECUTED",
    "subAmount": null,
    "subtitle": "Kauforder",
    "timestamp": "2023-12-07T06:59:36.156+0000",
    "title": "Anleihe Apr. 2026"
}
```

**Comment by pinzutu** [comment]
Thanks for sharing the bond event entry @evo-de. You can use the PR for a quick fix that leaves the shares csv field empty.

As I read the event entry, TR provides neither the number of bond shares nor the price of one bond share, and as we lack TR's exact discount rate formula, the coupon payment dates, and a high precision interest rate, I believe we can't precisely infer the number of shares bought as of now (please correct me if my understanding is wrong).

Also, as there might be other bond related events that are currently not supported, I would suggest renaming the issue to something like "Support for bonds" to collect such issues.
