### ISSUE TITLE
TypeError for timestamp

### ISSUE THREAD

**Issue by HSGEV** [pytr-org/pytr#78]
**Description of the bug**
Traceback (most recent call last):
  File "/Users/XXXX/.local/bin/pytr", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/XXXXXX/.local/pipx/venvs/pytr/lib/python3.12/site-packages/pytr/main.py", line 211, in main
    asyncio.get_event_loop().run_until_complete(dl.dl_loop())
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/XXXXX/.local/pipx/venvs/pytr/lib/python3.12/site-packages/pytr/dl.py", line 80, in dl_loop
    await self.tl.get_next_timeline_activity_log(response, max_age_timestamp=self.since_timestamp)
  File "/Users/XXXXXX/.local/pipx/venvs/pytr/lib/python3.12/site-packages/pytr/utils.py", line 332, in get_next_timeline_activity_log
    await self._get_timeline_details(5, max_age_timestamp=max_age_timestamp)
  File "/Users/XXXX/.local/pipx/venvs/pytr/lib/python3.12/site-packages/pytr/utils.py", line 354, in _get_timeline_details
    if max_age_timestamp != 0 and event['timestamp'] > max_age_timestamp:
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'str' and 'float'

**To Reproduce**
Start Sync

**Environment**

- OS: macOS
- pytr version: 0.1.9 (Latest Gitlab)

**Comment by Katzmann1983** [comment]
Fixed. Thank you
